table 'Bulk Purchase Analysis'
	lineageTag: b5f01db9-4500-41dd-9aaa-394fe803edf9

	column OrderSize
		dataType: string
		lineageTag: 7dbeb96c-8334-4025-ab50-7cf80fb09422
		summarizeBy: none
		sourceColumn: OrderSize

	column AverageUnitPurchasePrice
		dataType: double
		lineageTag: f9da0976-8c4c-4bf0-82ba-ff38b12722d7
		summarizeBy: sum
		sourceColumn: AverageUnitPurchasePrice

	column MedianUnitPurchasePrice
		dataType: double
		lineageTag: b4279765-5f11-40e4-bd47-0da6c0fc6dc6
		summarizeBy: sum
		sourceColumn: MedianUnitPurchasePrice

	column ItemCount
		dataType: int64
		lineageTag: beae4c89-7f1d-4ce7-9382-a4143a002818
		summarizeBy: sum
		sourceColumn: ItemCount

	partition 'Bulk Purchase Analysis Partition' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\\LOCAL_DISK_E\\DATA_ANALYSIS\\Capstone_Projects\\2\\Vendor_Performance_Projects\\reports\\powerbi_data\\bulk_purchase_analysis.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"OrderSize", type text}, {"AverageUnitPurchasePrice", type number}, {"MedianUnitPurchasePrice", type number}, {"ItemCount", Int64.Type}})
				in
				    #"Changed Type"

