table 'Top 10 Vendors By Sales'
	lineageTag: 3ead57a8-186b-4f9c-9c13-2f1a7ce7eb16

	column Rank
		dataType: int64
		lineageTag: 013c4bf3-0d01-4d96-97b4-9a795e11b64a
		summarizeBy: sum
		sourceColumn: Rank

	column VendorName
		dataType: string
		lineageTag: a82ab140-6ae9-4d84-955d-f86678c11c98
		summarizeBy: none
		sourceColumn: VendorName

	column TotalSalesDollars
		dataType: double
		lineageTag: b112097d-1e61-4367-a40a-0b40d378b241
		summarizeBy: sum
		sourceColumn: TotalSalesDollars

	partition 'Top 10 Vendors By Sales Partition' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\\LOCAL_DISK_E\\DATA_ANALYSIS\\Capstone_Projects\\2\\Vendor_Performance_Projects\\reports\\powerbi_data\\top_10_vendors_by_sales.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Rank", Int64.Type}, {"VendorName", type text}, {"TotalSalesDollars", type number}})
				in
				    #"Changed Type"

