table 'Top 10 Unsold Inventory Value'
	lineageTag: 1b6fe61a-944e-4d04-8522-bdc27f39163c

	column Rank
		dataType: int64
		lineageTag: 241afacb-1f42-4b6a-ab44-75dae611e9bc
		summarizeBy: sum
		sourceColumn: Rank

	column VendorName
		dataType: string
		lineageTag: 03efcd36-a2c2-4754-96a9-475cb9510123
		summarizeBy: none
		sourceColumn: VendorName

	column UnsoldInventoryValue
		dataType: double
		lineageTag: fcf57656-7687-47be-981c-715133c0f298
		summarizeBy: sum
		sourceColumn: UnsoldInventoryValue

	partition 'Top 10 Unsold Inventory Value Partition' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\\LOCAL_DISK_E\\DATA_ANALYSIS\\Capstone_Projects\\2\\Vendor_Performance_Projects\\reports\\powerbi_data\\top_10_unsold_inventory_value.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Rank", Int64.Type}, {"VendorName", type text}, {"UnsoldInventoryValue", type number}})
				in
				    #"Changed Type"

